server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: <your git sc-config-repo>
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka